### ISSUE TITLE
I loaded my pcd file, but the result seemed wrong

### ISSUE THREAD

**Issue by TheRunningHorse** [ThomasWestfechtel/StairwayDetectionGUI#1]
which parameter should I turn?
![2020-04-09 09-23-45屏幕截图](https://user-images.githubusercontent.com/62589403/78848302-edd86200-7a43-11ea-88fe-5a84bfb12e29.png)
![2020-04-09 09-24-03屏幕截图](https://user-images.githubusercontent.com/62589403/78848310-f4ff7000-7a43-11ea-9616-c3e364acd722.png)

**Comment by ThomasWestfechtel** [comment]
It seems the z axis is not aligned in your pcd file.
